server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmic?useSSL=false
    username: root
    password: pmic
    hikari:
      maximum-pool-size: 5
      pool-name: pmic-connection-pool
      connection-timeout: 5000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false    
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost:5672
    username: guest
    password: guest
    
camel:
  dataformat:
    json-jackson:
      object-mapper: jacksonObjectMapper
  springboot:
    trace-formatter-show-body: true
    trace-formatter-show-headers: true
    tracing: false   

ship:
  exchange: ship-exchange
  exchange-type: direct
  routing-key: ship-orders
  queue: ship-queue
  consumers: 5

ship-route: rabbitmq:${ship.exchange}?exchangeType=${ship.exchange-type}&routingKey=${ship.routing-key}&queue=${ship.queue}&concurrentConsumers=${ship.consumers}&addresses=${spring.rabbitmq.addresses}&threadPoolSize=${ship.consumers}&durable=true&autoAck=false&autoDelete=false&connectionFactory=#pmicRabbitConnectionFactory&prefetchEnabled=true&prefetchCount=1
